<?php
include"cabecera.inc.php";
include"cabecera2.inc.php";
include"menu.inc.php";
include"menu_video.inc.php";
include"cuerpo_inicial.inc.php";
include"footer.inc.php";
include"cuerpo_final.inc.php";
?>